apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: offerspub
  name: offerspub
spec:
  containers:
  - image: devminnu/offerspub
    name: offerspub
    ports:
    - containerPort: 30003
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
