apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: offerspub
  name: offerspub
spec:
  ports:
  - port: 30003
    protocol: TCP
    targetPort: 30003
    nodePort: 30003
  selector:
    app: offerspub
  type: NodePort
status:
  loadBalancer: {}
