apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  ports:
  - port: 5672
    protocol: TCP
    targetPort: 5672
    name: s-port
  - port: 15672
    protocol: TCP
    targetPort: 15672
    name: q-port
  selector:
    run: rabbitmq
status:
  loadBalancer: {}
---
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  containers:
  - image: rabbitmq:3-management
    name: rabbitmq
    ports:
    - containerPort: 5672
    - containerPort: 15672
    resources: {}
    envFrom:
    - secretRef:
        name: rabbitmq-secret
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
