apiVersion: v1
data:
  RABBIT_MQ_HOST: cmFiYml0bXE=
  RABBIT_MQ_PASSWORD: Z3Vlc3Q=
  RABBIT_MQ_PORT: NTY3Mg==
  RABBIT_MQ_USER: Z3Vlc3Q=
kind: Secret
metadata:
  creationTimestamp: null
  name: rabbitmq-secret
